import {
    IconAssembly,
    IconBuildingStore,
    IconBuildingWarehouse,
    IconCheckupList,
    IconPackage,
    IconTruckDelivery,
} from '@tabler/icons-react'

import { ItemInterface } from '.'

const dashboard: ItemInterface = {
    id: 'finishedgood',
    title: 'Finished Goods',
    type: 'group',
    allowedTypes: ['oqc', 'ppc'],
    children: [
        {
            id: 'finishedgood-inventory',
            title: 'Inventory',
            type: 'item',
            url: '/finishedGoods',
            icon: IconBuildingWarehouse,
            urls: [
                '/finishedGoods',
                '/finishedGoods/new',
                '/finishedGoods/edit',
            ],
            allowedTypes: ['oqc', 'ppc'],
        },
        {
            id: 'finishedgood-customer',
            title: 'Customer',
            type: 'item',
            url: '/customers',
            icon: IconBuildingStore,
            urls: ['/customers', '/customers/new', '/customers/edit'],
            allowedTypes: ['ppc'],
        },
        {
            id: 'finishedgood-salesOrders',
            title: 'Sales Orders',
            type: 'item',
            url: '/salesOrders',
            icon: IconPackage,
            urls: ['/salesOrders', '/salesOrders/new', '/salesOrders/edit'],
            allowedTypes: ['ppc'],
        },
        {
            id: 'finishedgood-outwards',
            title: 'Outwards',
            type: 'group',
            allowedTypes: ['oqc', 'ppc'],
            children: [
                {
                    id: 'finishedgood-outwards-production',
                    title: 'Production',
                    type: 'item',
                    url: '/outwards/production',
                    icon: IconAssembly,
                    urls: ['/outwards/production'],
                    allowedTypes: ['ppc'],
                },
                {
                    id: 'finishedgood-outwards-qualityCheck',
                    title: 'Quality Check',
                    type: 'item',
                    url: '/outwards/qualityCheck',
                    icon: IconCheckupList,
                    urls: ['/outwards/qualityCheck'],
                    allowedTypes: ['oqc', 'ppc'],
                },
                {
                    id: 'finishedgood-outwards-dispatch',
                    title: 'Dispatch',
                    type: 'item',
                    url: '/outwards/dispatch',
                    icon: IconTruckDelivery,
                    urls: ['/outwards/dispatch'],
                    allowedTypes: ['ppc'],
                },
            ],
        },
        {
            id: 'finishedgood-report',
            title: 'Reports',
            type: 'group',
            allowedTypes: ['oqc', 'ppc'],
            children: [
                {
                    id: 'finishedgood-report-byid',
                    title: 'By Unique Identifier',
                    type: 'item',
                    url: '/finishedGoods/report/byId',
                    urls: ['/finishedGoods/report/byId'],
                    allowedTypes: ['oqc', 'ppc'],
                },
                {
                    id: 'finishedgood-report-byso',
                    title: 'By Sales Order',
                    type: 'item',
                    url: '/finishedGoods/report/bySo',
                    urls: ['/finishedGoods/report/bySo'],
                    allowedTypes: ['ppc'],
                },
                {
                    id: 'finishedgood-report-production',
                    title: 'Production',
                    type: 'item',
                    url: '/finishedGoods/report/production',
                    urls: ['/finishedGoods/report/production'],
                    allowedTypes: ['ppc'],
                },
                {
                    id: 'finishedgood-report-dispatch',
                    title: 'Dispatch',
                    type: 'item',
                    url: '/finishedGoods/report/dispatch',
                    urls: ['/finishedGoods/report/dispatch'],
                    allowedTypes: ['ppc'],
                },
                {
                    id: 'finishedgood-report-productiontracker',
                    title: 'Production Tracker',
                    type: 'item',
                    url: '/finishedGoods/report/productionTracker',
                    urls: ['/finishedGoods/report/productionTracker'],
                    allowedTypes: ['ppc'],
                },
                {
                    id: 'finishedgood-report-dispatchtracker',
                    title: 'Dispatch Tracker',
                    type: 'item',
                    url: '/finishedGoods/report/dispatchTracker',
                    urls: ['/finishedGoods/report/dispatchTracker'],
                    allowedTypes: ['ppc'],
                },
                {
                    id: 'finishedgood-report-manpowerefficiency',
                    title: 'Manpower Efficiency',
                    type: 'item',
                    url: '/finishedGoods/report/manpowerEfficiency',
                    urls: ['/finishedGoods/report/manpowerEfficiency'],
                    allowedTypes: ['ppc'],
                },
            ],
        },
    ],
}

export default dashboard
